services:
  bridge:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bridge_mqtt_service
    ports:
      - "${API_PORT:-8000}:${API_PORT:-8000}"
    env_file:
      - .env
    restart: unless-stopped
